language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2
    - node
    - node_modules

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 +extension RANDR"
  - export DISPLAY=:99
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz"
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
  - "wget -q https://selenium-release.storage.googleapis.com/3.6/selenium-server-standalone-3.6.0.jar"
  - "java -Dwebdriver.gecko.driver=$PWD/geckodriver/geckodriver -jar selenium-server-standalone-3.6.0.jar &"
  - sleep 5

install: /bin/true

script: ./mvnw verify -B -Djava.util.logging.config.file="src/test/resources/logging.properties"

after_success:
  - bash <(curl -s https://codecov.io/bash)
