/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.jooq.tables;


import de.vorb.platon.jooq.AcumosComment;
import de.vorb.platon.jooq.Keys;
import de.vorb.platon.jooq.tables.records.PropertyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Property extends TableImpl<PropertyRecord> {

    private static final long serialVersionUID = 857036894;

    /**
     * The reference instance of <code>ACUMOS_COMMENT.PROPERTY</code>
     */
    public static final Property PROPERTY = new Property();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PropertyRecord> getRecordType() {
        return PropertyRecord.class;
    }

    /**
     * The column <code>ACUMOS_COMMENT.PROPERTY._KEY</code>.
     */
    public final TableField<PropertyRecord, String> _KEY = createField("_KEY", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>ACUMOS_COMMENT.PROPERTY.VALUE</code>.
     */
    public final TableField<PropertyRecord, String> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

    /**
     * Create a <code>ACUMOS_COMMENT.PROPERTY</code> table reference
     */
    public Property() {
        this("PROPERTY", null);
    }

    /**
     * Create an aliased <code>ACUMOS_COMMENT.PROPERTY</code> table reference
     */
    public Property(String alias) {
        this(alias, PROPERTY);
    }

    private Property(String alias, Table<PropertyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Property(String alias, Table<PropertyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AcumosComment.ACUMOS_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PropertyRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PropertyRecord>> getKeys() {
        return Arrays.<UniqueKey<PropertyRecord>>asList(Keys.CONSTRAINT_E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Property as(String alias) {
        return new Property(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Property rename(String name) {
        return new Property(name, null);
    }
}
