/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.jooq;


import de.vorb.platon.jooq.tables.Comment;
import de.vorb.platon.jooq.tables.Property;
import de.vorb.platon.jooq.tables.Thread;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcumosComment extends SchemaImpl {

    private static final long serialVersionUID = -775725872;

    /**
     * The reference instance of <code>ACUMOS_COMMENT</code>
     */
    public static final AcumosComment ACUMOS_COMMENT = new AcumosComment();

    /**
     * The table <code>ACUMOS_COMMENT.COMMENT</code>.
     */
    public final Comment COMMENT = de.vorb.platon.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>ACUMOS_COMMENT.PROPERTY</code>.
     */
    public final Property PROPERTY = de.vorb.platon.jooq.tables.Property.PROPERTY;

    /**
     * The table <code>ACUMOS_COMMENT.THREAD</code>.
     */
    public final Thread THREAD = de.vorb.platon.jooq.tables.Thread.THREAD;

    /**
     * No further instances allowed
     */
    private AcumosComment() {
        super("ACUMOS_COMMENT", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_535E8D49_CA03_4917_AEF5_D70F272F112E,
            Sequences.SYSTEM_SEQUENCE_ABB044ED_729F_4888_8F7C_38B18187E707);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            Property.PROPERTY,
            Thread.THREAD);
    }
}
