/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in ACUMOS_COMMENT
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>ACUMOS_COMMENT.SYSTEM_SEQUENCE_535E8D49_CA03_4917_AEF5_D70F272F112E</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_535E8D49_CA03_4917_AEF5_D70F272F112E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_535E8D49_CA03_4917_AEF5_D70F272F112E", AcumosComment.ACUMOS_COMMENT, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ACUMOS_COMMENT.SYSTEM_SEQUENCE_ABB044ED_729F_4888_8F7C_38B18187E707</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_ABB044ED_729F_4888_8F7C_38B18187E707 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_ABB044ED_729F_4888_8F7C_38B18187E707", AcumosComment.ACUMOS_COMMENT, org.jooq.impl.SQLDataType.BIGINT);
}
