/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.jooq;


import de.vorb.platon.jooq.tables.Comment;
import de.vorb.platon.jooq.tables.Property;
import de.vorb.platon.jooq.tables.Thread;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ACUMOS_COMMENT
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACUMOS_COMMENT.COMMENT</code>.
     */
    public static final Comment COMMENT = de.vorb.platon.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>ACUMOS_COMMENT.PROPERTY</code>.
     */
    public static final Property PROPERTY = de.vorb.platon.jooq.tables.Property.PROPERTY;

    /**
     * The table <code>ACUMOS_COMMENT.THREAD</code>.
     */
    public static final Thread THREAD = de.vorb.platon.jooq.tables.Thread.THREAD;
}
