/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.jooq.tables.records;


import de.vorb.platon.jooq.tables.Property;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyRecord extends UpdatableRecordImpl<PropertyRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1432565611;

    /**
     * Setter for <code>ACUMOS_COMMENT.PROPERTY._KEY</code>.
     */
    public PropertyRecord set_Key(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ACUMOS_COMMENT.PROPERTY._KEY</code>.
     */
    @NotNull
    @Size(max = 32)
    public String get_Key() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ACUMOS_COMMENT.PROPERTY.VALUE</code>.
     */
    public PropertyRecord setValue(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ACUMOS_COMMENT.PROPERTY.VALUE</code>.
     */
    @NotNull
    @Size(max = 256)
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Property.PROPERTY._KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Property.PROPERTY.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return get_Key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value1(String value) {
        set_Key(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertyRecord
     */
    public PropertyRecord() {
        super(Property.PROPERTY);
    }

    /**
     * Create a detached, initialised PropertyRecord
     */
    public PropertyRecord(String _Key, String value) {
        super(Property.PROPERTY);

        set(0, _Key);
        set(1, value);
    }
}
